services:
  # A web service
  - type: web
    name: fifa-vis-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5